/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CropsRouteImport } from './routes/crops'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FertilizersRouteImport } from './routes/fertilizers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PesticidesRouteImport } from './routes/pesticides'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as WeatherRouteImport } from './routes/weather'
import { Route as CropsCropIdRouteImport } from './routes/crops.$cropId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsRoute = CropsRouteImport.update({
  id: '/crops',
  path: '/crops',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FertilizersRoute = FertilizersRouteImport.update({
  id: '/fertilizers',
  path: '/fertilizers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PesticidesRoute = PesticidesRouteImport.update({
  id: '/pesticides',
  path: '/pesticides',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const WeatherRoute = WeatherRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const CropsCropIdRoute = CropsCropIdRouteImport.update({
  id: '/$cropId',
  path: '/$cropId',
  getParentRoute: () => CropsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/crops': typeof CropsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/fertilizers': typeof FertilizersRoute
  '/login': typeof LoginRoute
  '/pesticides': typeof PesticidesRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/weather': typeof WeatherRoute
  '/crops/$cropId': typeof CropsCropIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/crops': typeof CropsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/fertilizers': typeof FertilizersRoute
  '/login': typeof LoginRoute
  '/pesticides': typeof PesticidesRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/weather': typeof WeatherRoute
  '/crops/$cropId': typeof CropsCropIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/crops': typeof CropsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/fertilizers': typeof FertilizersRoute
  '/login': typeof LoginRoute
  '/pesticides': typeof PesticidesRoute
  '/register': typeof RegisterRoute
  '/scan': typeof ScanRoute
  '/weather': typeof WeatherRoute
  '/crops/$cropId': typeof CropsCropIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/crops'
    | '/dashboard'
    | '/fertilizers'
    | '/login'
    | '/pesticides'
    | '/register'
    | '/scan'
    | '/weather'
    | '/crops/$cropId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/crops'
    | '/dashboard'
    | '/fertilizers'
    | '/login'
    | '/pesticides'
    | '/register'
    | '/scan'
    | '/weather'
    | '/crops/$cropId'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/crops'
    | '/dashboard'
    | '/fertilizers'
    | '/login'
    | '/pesticides'
    | '/register'
    | '/scan'
    | '/weather'
    | '/crops/$cropId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  CropsRoute: typeof CropsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  FertilizersRoute: typeof FertilizersRoute
  LoginRoute: typeof LoginRoute
  PesticidesRoute: typeof PesticidesRoute
  RegisterRoute: typeof RegisterRoute
  ScanRoute: typeof ScanRoute
  WeatherRoute: typeof WeatherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops': {
      id: '/crops'
      path: '/crops'
      fullPath: '/crops'
      preLoaderRoute: typeof CropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fertilizers': {
      id: '/fertilizers'
      path: '/fertilizers'
      fullPath: '/fertilizers'
      preLoaderRoute: typeof FertilizersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesticides': {
      id: '/pesticides'
      path: '/pesticides'
      fullPath: '/pesticides'
      preLoaderRoute: typeof PesticidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crops/$cropId': {
      id: '/crops/$cropId'
      path: '/$cropId'
      fullPath: '/crops/$cropId'
      preLoaderRoute: typeof CropsCropIdRouteImport
      parentRoute: typeof CropsRoute
    }
  }
}

interface CropsRouteChildren {
  CropsCropIdRoute: typeof CropsCropIdRoute
}

const CropsRouteChildren: CropsRouteChildren = {
  CropsCropIdRoute: CropsCropIdRoute,
}

const CropsRouteWithChildren = CropsRoute._addFileChildren(CropsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  CropsRoute: CropsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  FertilizersRoute: FertilizersRoute,
  LoginRoute: LoginRoute,
  PesticidesRoute: PesticidesRoute,
  RegisterRoute: RegisterRoute,
  ScanRoute: ScanRoute,
  WeatherRoute: WeatherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
